name: Push Validation

on:
  push:
    branches:
      - '**'
    paths:
      - 'src/**'
      - 'tests/**'
      - '.devcontainer/**'
      - '.github/workflows/**'

  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Display dotnet information
      run: |
        dotnet --version
        dotnet --info
        dotnet --list-sdks
        dotnet --list-runtimes

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
